### ISSUE TITLE
wont launch

### ISSUE THREAD

**Issue by midvightmirage** [ekulxam/enchancement-unbound#1]
### Mod version (NOT Minecraft version)

enchancement_unbound-1.0.6+1.20.6-r5

### A description of the issue

when i launch the game, i get an error and the entire process ends entirely

the only mods in my folder are
- enchancement_unbound-1.0.6+1.20.6-r5
- enchancement-1.20.6-r5
- fabric-api-0.100.0+1.20.6
and they are all loaded

I'm using LWJGL 3.3.3 on Minecraft 1.20.6, and Fabric Loader 0.15.11

### Log or crash report

https://mclo.gs/bHmXQCl

**Comment by ekulxam** [comment]
Sorry, this is a known issue. I'll fix it once I get around it fixing all the remaps.
